#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside

sudo apt -y update
sudo apt -y install nginx
echo "Hello World!" | sudo tee /var/www/index.html
sudo service nginx start
