#!/usr/bin/env bash
# Script displaying numbers from 1-100 in list format
# it displays FizzBuzz when the number is a multiple of 3 and 5
# Fizz when the number is multiple of 3, Buzz if the number is a multiple of 5
# Otherwise, it displays the number
i=1
while [ $i -le 100 ];
do
	if (( i % 3 == 0 &&  i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo $i
	fi
	((i++))
done
