#!/usr/bin/env bash
# Script displays content of the file /etc/passwd, using the while loop + IFS
# In story like format

while IFS=':' read -r username password uid gid info home SHELL;
do
	echo "The user $username is part of the $gid gang,"\
	"lives in $home and rides $SHELL."\
	"$uid's place is protected by the passcode $password,"\
	"more info about the user here: $info"
done < "/etc/passwd"
