#!/usr/bin/env bash
# This script is looping from 1 to 10 using while loop
# It is displaying "bad luck" on the 4th iteration & "good luck" on the 8th
# and "Best School" for the other iterations.
i=1
while [ $i -le 10 ];
do
	if [ $i == 4 ];
	then
		echo "bad luck"
	elif [ $i == 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
