#!/usr/bin/env bash
# This script displays the contents of the current directory in list format
# where only the part of the name after the first dash is displayed
# using for loop
list=$(ls)
for i in $list $CDPTH;
do
	echo "$i" | cut -d '-' -f2
done
