#!/usr/bin/env bash                                                            
# This script set up Nginx to run as nginx user                                                          
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 744 /etc/nginx/nginx.conf
sudo -u nginx 
service nginx restart
